# Generated by Django 6.0.2 on 2026-06-10 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_document_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-updated_at']},
        ),
    ]
